# 6502 (2A03) decode table: one entry per opcode 0x00-0xFF.
# op: operation (official + unofficial), mode: addressing mode,
# cycles: base cycle count, penalty: +1 cycle when an indexed read
# crosses a page boundary (stores and RMW ops pay the fixed cost instead).
# Branch extras (+1 taken, +1 taken-and-crossed) are handled by the executor.
# References: https://www.nesdev.org/wiki/CPU_unofficial_opcodes
#             https://www.oxyron.de/html/opcodes02.html

Op : [
    # Official
    Adc, And, Asl, Bcc, Bcs, Beq, Bit, Bmi, Bne, Bpl, Brk, Bvc, Bvs,
    Clc, Cld, Cli, Clv, Cmp, Cpx, Cpy, Dec, Dex, Dey, Eor, Inc, Inx, Iny,
    Jmp, Jsr, Lda, Ldx, Ldy, Lsr, Nop, Ora, Pha, Php, Pla, Plp, Rol, Ror,
    Rti, Rts, Sbc, Sec, Sed, Sei, Sta, Stx, Sty, Tax, Tay, Tsx, Txa, Txs, Tya,
    # Unofficial
    Ahx, Alr, Anc, Arr, Axs, Dcp, Isc, Kil, Las, Lax, Lxa, Rla, Rra, Sax,
    Shx, Shy, Slo, Sre, Tas, Xaa,
]

Mode : [
    Implied,
    Accumulator,
    Immediate,
    ZeroPage,
    ZeroPageX,
    ZeroPageY,
    Absolute,
    AbsoluteX,
    AbsoluteY,
    Indirect,
    IndexedIndirect, # (d,X)
    IndirectIndexed, # (d),Y
    Relative,
]

Entry : {
    op : Op,
    mode : Mode,
    cycles : U8,
    penalty : Bool,
}

Instruction :: [].{
    make : Op, Mode, U8, Bool -> Entry
    make = |op, mode, cycles, penalty| { op: op, mode: mode, cycles: cycles, penalty: penalty }

    lookup : U8 -> Entry
    lookup = |byte|
        match byte {
            0x00 => make(Brk, Implied, 7, Bool.False)
            0x01 => make(Ora, IndexedIndirect, 6, Bool.False)
            0x02 => make(Kil, Implied, 11, Bool.False)
            0x03 => make(Slo, IndexedIndirect, 8, Bool.False)
            0x04 => make(Nop, ZeroPage, 3, Bool.False)
            0x05 => make(Ora, ZeroPage, 3, Bool.False)
            0x06 => make(Asl, ZeroPage, 5, Bool.False)
            0x07 => make(Slo, ZeroPage, 5, Bool.False)
            0x08 => make(Php, Implied, 3, Bool.False)
            0x09 => make(Ora, Immediate, 2, Bool.False)
            0x0A => make(Asl, Accumulator, 2, Bool.False)
            0x0B => make(Anc, Immediate, 2, Bool.False)
            0x0C => make(Nop, Absolute, 4, Bool.False)
            0x0D => make(Ora, Absolute, 4, Bool.False)
            0x0E => make(Asl, Absolute, 6, Bool.False)
            0x0F => make(Slo, Absolute, 6, Bool.False)
            0x10 => make(Bpl, Relative, 2, Bool.False)
            0x11 => make(Ora, IndirectIndexed, 5, Bool.True)
            0x12 => make(Kil, Implied, 11, Bool.False)
            0x13 => make(Slo, IndirectIndexed, 8, Bool.False)
            0x14 => make(Nop, ZeroPageX, 4, Bool.False)
            0x15 => make(Ora, ZeroPageX, 4, Bool.False)
            0x16 => make(Asl, ZeroPageX, 6, Bool.False)
            0x17 => make(Slo, ZeroPageX, 6, Bool.False)
            0x18 => make(Clc, Implied, 2, Bool.False)
            0x19 => make(Ora, AbsoluteY, 4, Bool.True)
            0x1A => make(Nop, Implied, 2, Bool.False)
            0x1B => make(Slo, AbsoluteY, 7, Bool.False)
            0x1C => make(Nop, AbsoluteX, 4, Bool.True)
            0x1D => make(Ora, AbsoluteX, 4, Bool.True)
            0x1E => make(Asl, AbsoluteX, 7, Bool.False)
            0x1F => make(Slo, AbsoluteX, 7, Bool.False)
            0x20 => make(Jsr, Absolute, 6, Bool.False)
            0x21 => make(And, IndexedIndirect, 6, Bool.False)
            0x22 => make(Kil, Implied, 11, Bool.False)
            0x23 => make(Rla, IndexedIndirect, 8, Bool.False)
            0x24 => make(Bit, ZeroPage, 3, Bool.False)
            0x25 => make(And, ZeroPage, 3, Bool.False)
            0x26 => make(Rol, ZeroPage, 5, Bool.False)
            0x27 => make(Rla, ZeroPage, 5, Bool.False)
            0x28 => make(Plp, Implied, 4, Bool.False)
            0x29 => make(And, Immediate, 2, Bool.False)
            0x2A => make(Rol, Accumulator, 2, Bool.False)
            0x2B => make(Anc, Immediate, 2, Bool.False)
            0x2C => make(Bit, Absolute, 4, Bool.False)
            0x2D => make(And, Absolute, 4, Bool.False)
            0x2E => make(Rol, Absolute, 6, Bool.False)
            0x2F => make(Rla, Absolute, 6, Bool.False)
            0x30 => make(Bmi, Relative, 2, Bool.False)
            0x31 => make(And, IndirectIndexed, 5, Bool.True)
            0x32 => make(Kil, Implied, 11, Bool.False)
            0x33 => make(Rla, IndirectIndexed, 8, Bool.False)
            0x34 => make(Nop, ZeroPageX, 4, Bool.False)
            0x35 => make(And, ZeroPageX, 4, Bool.False)
            0x36 => make(Rol, ZeroPageX, 6, Bool.False)
            0x37 => make(Rla, ZeroPageX, 6, Bool.False)
            0x38 => make(Sec, Implied, 2, Bool.False)
            0x39 => make(And, AbsoluteY, 4, Bool.True)
            0x3A => make(Nop, Implied, 2, Bool.False)
            0x3B => make(Rla, AbsoluteY, 7, Bool.False)
            0x3C => make(Nop, AbsoluteX, 4, Bool.True)
            0x3D => make(And, AbsoluteX, 4, Bool.True)
            0x3E => make(Rol, AbsoluteX, 7, Bool.False)
            0x3F => make(Rla, AbsoluteX, 7, Bool.False)
            0x40 => make(Rti, Implied, 6, Bool.False)
            0x41 => make(Eor, IndexedIndirect, 6, Bool.False)
            0x42 => make(Kil, Implied, 11, Bool.False)
            0x43 => make(Sre, IndexedIndirect, 8, Bool.False)
            0x44 => make(Nop, ZeroPage, 3, Bool.False)
            0x45 => make(Eor, ZeroPage, 3, Bool.False)
            0x46 => make(Lsr, ZeroPage, 5, Bool.False)
            0x47 => make(Sre, ZeroPage, 5, Bool.False)
            0x48 => make(Pha, Implied, 3, Bool.False)
            0x49 => make(Eor, Immediate, 2, Bool.False)
            0x4A => make(Lsr, Accumulator, 2, Bool.False)
            0x4B => make(Alr, Immediate, 2, Bool.False)
            0x4C => make(Jmp, Absolute, 3, Bool.False)
            0x4D => make(Eor, Absolute, 4, Bool.False)
            0x4E => make(Lsr, Absolute, 6, Bool.False)
            0x4F => make(Sre, Absolute, 6, Bool.False)
            0x50 => make(Bvc, Relative, 2, Bool.False)
            0x51 => make(Eor, IndirectIndexed, 5, Bool.True)
            0x52 => make(Kil, Implied, 11, Bool.False)
            0x53 => make(Sre, IndirectIndexed, 8, Bool.False)
            0x54 => make(Nop, ZeroPageX, 4, Bool.False)
            0x55 => make(Eor, ZeroPageX, 4, Bool.False)
            0x56 => make(Lsr, ZeroPageX, 6, Bool.False)
            0x57 => make(Sre, ZeroPageX, 6, Bool.False)
            0x58 => make(Cli, Implied, 2, Bool.False)
            0x59 => make(Eor, AbsoluteY, 4, Bool.True)
            0x5A => make(Nop, Implied, 2, Bool.False)
            0x5B => make(Sre, AbsoluteY, 7, Bool.False)
            0x5C => make(Nop, AbsoluteX, 4, Bool.True)
            0x5D => make(Eor, AbsoluteX, 4, Bool.True)
            0x5E => make(Lsr, AbsoluteX, 7, Bool.False)
            0x5F => make(Sre, AbsoluteX, 7, Bool.False)
            0x60 => make(Rts, Implied, 6, Bool.False)
            0x61 => make(Adc, IndexedIndirect, 6, Bool.False)
            0x62 => make(Kil, Implied, 11, Bool.False)
            0x63 => make(Rra, IndexedIndirect, 8, Bool.False)
            0x64 => make(Nop, ZeroPage, 3, Bool.False)
            0x65 => make(Adc, ZeroPage, 3, Bool.False)
            0x66 => make(Ror, ZeroPage, 5, Bool.False)
            0x67 => make(Rra, ZeroPage, 5, Bool.False)
            0x68 => make(Pla, Implied, 4, Bool.False)
            0x69 => make(Adc, Immediate, 2, Bool.False)
            0x6A => make(Ror, Accumulator, 2, Bool.False)
            0x6B => make(Arr, Immediate, 2, Bool.False)
            0x6C => make(Jmp, Indirect, 5, Bool.False)
            0x6D => make(Adc, Absolute, 4, Bool.False)
            0x6E => make(Ror, Absolute, 6, Bool.False)
            0x6F => make(Rra, Absolute, 6, Bool.False)
            0x70 => make(Bvs, Relative, 2, Bool.False)
            0x71 => make(Adc, IndirectIndexed, 5, Bool.True)
            0x72 => make(Kil, Implied, 11, Bool.False)
            0x73 => make(Rra, IndirectIndexed, 8, Bool.False)
            0x74 => make(Nop, ZeroPageX, 4, Bool.False)
            0x75 => make(Adc, ZeroPageX, 4, Bool.False)
            0x76 => make(Ror, ZeroPageX, 6, Bool.False)
            0x77 => make(Rra, ZeroPageX, 6, Bool.False)
            0x78 => make(Sei, Implied, 2, Bool.False)
            0x79 => make(Adc, AbsoluteY, 4, Bool.True)
            0x7A => make(Nop, Implied, 2, Bool.False)
            0x7B => make(Rra, AbsoluteY, 7, Bool.False)
            0x7C => make(Nop, AbsoluteX, 4, Bool.True)
            0x7D => make(Adc, AbsoluteX, 4, Bool.True)
            0x7E => make(Ror, AbsoluteX, 7, Bool.False)
            0x7F => make(Rra, AbsoluteX, 7, Bool.False)
            0x80 => make(Nop, Immediate, 2, Bool.False)
            0x81 => make(Sta, IndexedIndirect, 6, Bool.False)
            0x82 => make(Nop, Immediate, 2, Bool.False)
            0x83 => make(Sax, IndexedIndirect, 6, Bool.False)
            0x84 => make(Sty, ZeroPage, 3, Bool.False)
            0x85 => make(Sta, ZeroPage, 3, Bool.False)
            0x86 => make(Stx, ZeroPage, 3, Bool.False)
            0x87 => make(Sax, ZeroPage, 3, Bool.False)
            0x88 => make(Dey, Implied, 2, Bool.False)
            0x89 => make(Nop, Immediate, 2, Bool.False)
            0x8A => make(Txa, Implied, 2, Bool.False)
            0x8B => make(Xaa, Immediate, 2, Bool.False)
            0x8C => make(Sty, Absolute, 4, Bool.False)
            0x8D => make(Sta, Absolute, 4, Bool.False)
            0x8E => make(Stx, Absolute, 4, Bool.False)
            0x8F => make(Sax, Absolute, 4, Bool.False)
            0x90 => make(Bcc, Relative, 2, Bool.False)
            0x91 => make(Sta, IndirectIndexed, 6, Bool.False)
            0x92 => make(Kil, Implied, 11, Bool.False)
            0x93 => make(Ahx, IndirectIndexed, 6, Bool.False)
            0x94 => make(Sty, ZeroPageX, 4, Bool.False)
            0x95 => make(Sta, ZeroPageX, 4, Bool.False)
            0x96 => make(Stx, ZeroPageY, 4, Bool.False)
            0x97 => make(Sax, ZeroPageY, 4, Bool.False)
            0x98 => make(Tya, Implied, 2, Bool.False)
            0x99 => make(Sta, AbsoluteY, 5, Bool.False)
            0x9A => make(Txs, Implied, 2, Bool.False)
            0x9B => make(Tas, AbsoluteY, 5, Bool.False)
            0x9C => make(Shy, AbsoluteX, 5, Bool.False)
            0x9D => make(Sta, AbsoluteX, 5, Bool.False)
            0x9E => make(Shx, AbsoluteY, 5, Bool.False)
            0x9F => make(Ahx, AbsoluteY, 5, Bool.False)
            0xA0 => make(Ldy, Immediate, 2, Bool.False)
            0xA1 => make(Lda, IndexedIndirect, 6, Bool.False)
            0xA2 => make(Ldx, Immediate, 2, Bool.False)
            0xA3 => make(Lax, IndexedIndirect, 6, Bool.False)
            0xA4 => make(Ldy, ZeroPage, 3, Bool.False)
            0xA5 => make(Lda, ZeroPage, 3, Bool.False)
            0xA6 => make(Ldx, ZeroPage, 3, Bool.False)
            0xA7 => make(Lax, ZeroPage, 3, Bool.False)
            0xA8 => make(Tay, Implied, 2, Bool.False)
            0xA9 => make(Lda, Immediate, 2, Bool.False)
            0xAA => make(Tax, Implied, 2, Bool.False)
            0xAB => make(Lxa, Immediate, 2, Bool.False)
            0xAC => make(Ldy, Absolute, 4, Bool.False)
            0xAD => make(Lda, Absolute, 4, Bool.False)
            0xAE => make(Ldx, Absolute, 4, Bool.False)
            0xAF => make(Lax, Absolute, 4, Bool.False)
            0xB0 => make(Bcs, Relative, 2, Bool.False)
            0xB1 => make(Lda, IndirectIndexed, 5, Bool.True)
            0xB2 => make(Kil, Implied, 11, Bool.False)
            0xB3 => make(Lax, IndirectIndexed, 5, Bool.True)
            0xB4 => make(Ldy, ZeroPageX, 4, Bool.False)
            0xB5 => make(Lda, ZeroPageX, 4, Bool.False)
            0xB6 => make(Ldx, ZeroPageY, 4, Bool.False)
            0xB7 => make(Lax, ZeroPageY, 4, Bool.False)
            0xB8 => make(Clv, Implied, 2, Bool.False)
            0xB9 => make(Lda, AbsoluteY, 4, Bool.True)
            0xBA => make(Tsx, Implied, 2, Bool.False)
            0xBB => make(Las, AbsoluteY, 4, Bool.True)
            0xBC => make(Ldy, AbsoluteX, 4, Bool.True)
            0xBD => make(Lda, AbsoluteX, 4, Bool.True)
            0xBE => make(Ldx, AbsoluteY, 4, Bool.True)
            0xBF => make(Lax, AbsoluteY, 4, Bool.True)
            0xC0 => make(Cpy, Immediate, 2, Bool.False)
            0xC1 => make(Cmp, IndexedIndirect, 6, Bool.False)
            0xC2 => make(Nop, Immediate, 2, Bool.False)
            0xC3 => make(Dcp, IndexedIndirect, 8, Bool.False)
            0xC4 => make(Cpy, ZeroPage, 3, Bool.False)
            0xC5 => make(Cmp, ZeroPage, 3, Bool.False)
            0xC6 => make(Dec, ZeroPage, 5, Bool.False)
            0xC7 => make(Dcp, ZeroPage, 5, Bool.False)
            0xC8 => make(Iny, Implied, 2, Bool.False)
            0xC9 => make(Cmp, Immediate, 2, Bool.False)
            0xCA => make(Dex, Implied, 2, Bool.False)
            0xCB => make(Axs, Immediate, 2, Bool.False)
            0xCC => make(Cpy, Absolute, 4, Bool.False)
            0xCD => make(Cmp, Absolute, 4, Bool.False)
            0xCE => make(Dec, Absolute, 6, Bool.False)
            0xCF => make(Dcp, Absolute, 6, Bool.False)
            0xD0 => make(Bne, Relative, 2, Bool.False)
            0xD1 => make(Cmp, IndirectIndexed, 5, Bool.True)
            0xD2 => make(Kil, Implied, 11, Bool.False)
            0xD3 => make(Dcp, IndirectIndexed, 8, Bool.False)
            0xD4 => make(Nop, ZeroPageX, 4, Bool.False)
            0xD5 => make(Cmp, ZeroPageX, 4, Bool.False)
            0xD6 => make(Dec, ZeroPageX, 6, Bool.False)
            0xD7 => make(Dcp, ZeroPageX, 6, Bool.False)
            0xD8 => make(Cld, Implied, 2, Bool.False)
            0xD9 => make(Cmp, AbsoluteY, 4, Bool.True)
            0xDA => make(Nop, Implied, 2, Bool.False)
            0xDB => make(Dcp, AbsoluteY, 7, Bool.False)
            0xDC => make(Nop, AbsoluteX, 4, Bool.True)
            0xDD => make(Cmp, AbsoluteX, 4, Bool.True)
            0xDE => make(Dec, AbsoluteX, 7, Bool.False)
            0xDF => make(Dcp, AbsoluteX, 7, Bool.False)
            0xE0 => make(Cpx, Immediate, 2, Bool.False)
            0xE1 => make(Sbc, IndexedIndirect, 6, Bool.False)
            0xE2 => make(Nop, Immediate, 2, Bool.False)
            0xE3 => make(Isc, IndexedIndirect, 8, Bool.False)
            0xE4 => make(Cpx, ZeroPage, 3, Bool.False)
            0xE5 => make(Sbc, ZeroPage, 3, Bool.False)
            0xE6 => make(Inc, ZeroPage, 5, Bool.False)
            0xE7 => make(Isc, ZeroPage, 5, Bool.False)
            0xE8 => make(Inx, Implied, 2, Bool.False)
            0xE9 => make(Sbc, Immediate, 2, Bool.False)
            0xEA => make(Nop, Implied, 2, Bool.False)
            0xEB => make(Sbc, Immediate, 2, Bool.False)
            0xEC => make(Cpx, Absolute, 4, Bool.False)
            0xED => make(Sbc, Absolute, 4, Bool.False)
            0xEE => make(Inc, Absolute, 6, Bool.False)
            0xEF => make(Isc, Absolute, 6, Bool.False)
            0xF0 => make(Beq, Relative, 2, Bool.False)
            0xF1 => make(Sbc, IndirectIndexed, 5, Bool.True)
            0xF2 => make(Kil, Implied, 11, Bool.False)
            0xF3 => make(Isc, IndirectIndexed, 8, Bool.False)
            0xF4 => make(Nop, ZeroPageX, 4, Bool.False)
            0xF5 => make(Sbc, ZeroPageX, 4, Bool.False)
            0xF6 => make(Inc, ZeroPageX, 6, Bool.False)
            0xF7 => make(Isc, ZeroPageX, 6, Bool.False)
            0xF8 => make(Sed, Implied, 2, Bool.False)
            0xF9 => make(Sbc, AbsoluteY, 4, Bool.True)
            0xFA => make(Nop, Implied, 2, Bool.False)
            0xFB => make(Isc, AbsoluteY, 7, Bool.False)
            0xFC => make(Nop, AbsoluteX, 4, Bool.True)
            0xFD => make(Sbc, AbsoluteX, 4, Bool.True)
            0xFE => make(Inc, AbsoluteX, 7, Bool.False)
            0xFF => make(Isc, AbsoluteX, 7, Bool.False)
            _ => make(Kil, Implied, 11, Bool.False) # unreachable: all 256 byte values are listed above
        }
}

expect Instruction.lookup(0xA9).op == Lda
expect Instruction.lookup(0xA9).cycles == 2
expect Instruction.lookup(0x6C).mode == Indirect
expect Instruction.lookup(0xBD).penalty == Bool.True
expect Instruction.lookup(0x9D).penalty == Bool.False # STA abs,X pays the fixed 5
